# Generated by Django 3.1.4 on 2021-05-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEventList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('venue', models.CharField(max_length=30)),
                ('event_name', models.ForeignKey(limit_choices_to={'type': 'T'}, on_delete=django.db.models.deletion.CASCADE, to='registration.events')),
                ('team1', models.ForeignKey(limit_choices_to={'year': 2021}, on_delete=django.db.models.deletion.CASCADE, related_name='team11', to='registration.teamregistrationmodel')),
                ('team2', models.ForeignKey(limit_choices_to={'year': 2021}, on_delete=django.db.models.deletion.CASCADE, related_name='team12', to='registration.teamregistrationmodel')),
            ],
            options={
                'verbose_name_plural': 'Team Event List',
            },
        ),
        migrations.CreateModel(
            name='IndividualEventsList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fix', models.CharField(blank=True, max_length=100)),
                ('datetime', models.DateTimeField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.categories')),
                ('event', models.ForeignKey(limit_choices_to={'type': 'I'}, on_delete=django.db.models.deletion.CASCADE, to='registration.events')),
            ],
            options={
                'verbose_name_plural': 'Individual Events',
            },
        ),
    ]
