# Generated by Django 3.1.4 on 2021-05-09 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='GalleryFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Gallery Folder',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Notice',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=150)),
                ('mobile', models.CharField(max_length=10)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(upload_to='ImageGallery/')),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.galleryfolder')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
