# Generated by Django 3.1.4 on 2021-05-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
