# Generated by Django 3.1.4 on 2021-05-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_rules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryModel',
            new_name='ImageGallery',
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name_plural': 'Image Gallery'},
        ),
    ]
