# Generated by Django 3.1.4 on 2021-05-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='Male', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('tevent_id', models.AutoField(primary_key=True, serialize=False)),
                ('events', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('T', 'Team'), ('I', 'Individual')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.categories')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='PermanentTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
                ('captain', models.CharField(max_length=30)),
                ('vice_captain', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('event_name', models.ForeignKey(limit_choices_to={'type': 'T'}, on_delete=django.db.models.deletion.CASCADE, to='registration.events')),
            ],
            options={
                'verbose_name_plural': 'Permanent Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamRegistrationmodel',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2021)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.categories')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.permanentteam')),
            ],
            options={
                'verbose_name_plural': 'Team Registration',
            },
        ),
        migrations.CreateModel(
            name='TeamPlayers',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=30)),
                ('id_number', models.CharField(default=0, max_length=6)),
                ('is_active', models.BooleanField(default=False)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.permanentteam')),
            ],
            options={
                'verbose_name_plural': 'Team Players',
            },
        ),
        migrations.CreateModel(
            name='IndividualRegistration',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('idnum', models.IntegerField()),
                ('year', models.IntegerField(default=2021)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('event', models.ForeignKey(limit_choices_to={'type': 'I'}, on_delete=django.db.models.deletion.CASCADE, to='registration.events')),
            ],
            options={
                'verbose_name_plural': 'Individual Registrations',
            },
        ),
    ]
