# Generated by Django 3.1.4 on 2021-05-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='rule',
            field=models.TextField(),
        ),
    ]
